version: '3'

services:
###> doctrine/doctrine-bundle ###
  app:
    image: kentuckyss/symfony-api-skeleton:latest
    ports:
      - "8080:80"
    environment:
      DATABASE_URL: mysql://${MYSQL_USER:-symfony}:${MYSQL_PASSWORD:-symfony}@mysql:3306/${MYSQL_DATABASE:-app}

  mysql:
        image: 'mysql/mysql-server:8.0'
        restart: always
        container_name: symfony-api-expenses-mysql
        ports:
            - '3306:3306'
        environment:
            MYSQL_ROOT_PASSWORD: admin
            MYSQL_DATABASE: '${DB_DATABASE:-app}'
            MYSQL_USER: '${DB_USERNAME:-symfony}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-symfony}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        volumes:
            - ./init:/docker-entrypoint-initdb.d
            # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
            # - ./docker/db/data:/var/lib/postgresql/data:rw
        networks:
            - symfony-api-expenses
        healthcheck:
            test: ["CMD", "mysqladmin", "ping", "-p${DB_PASSWORD}"]
            retries: 3
            timeout: 5s

  phpmyadmin:
        image: phpmyadmin
        restart: always
        container_name: symfony-api-expenses-phpmyadmin
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-symfony}'
        links:
            - mysql:mysql
        ports:
            - "8008:80"
        networks:
            - symfony-api-expenses
        depends_on:
            - mysql
###< doctrine/doctrine-bundle ###

networks:
    symfony-api-expenses:
        driver: bridge
volumes:
###> doctrine/doctrine-bundle ###
  db-data:
###< doctrine/doctrine-bundle ###