name: Test Docker Build and Run
on:
    push:
        branches:
            - main
            - dev
            - hotfix
    pull_request:
        branches:
            - main
            - dev
            - hotfix

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build and Run Docker Compose
      uses: actions/checkout@v3
    # - run: docker build -t my-app . -f ./docker/Dockerfile && docker run -d -p 8080:8080 my-app
    - run: docker compose up -d
      # Attendre que l'application soit démarrée
      # avant de lancer les tests
    # - env:
    #     WAIT_TIME: 10
    - run: echo "Waiting for the app to start..." && sleep 10
    #   # Lancement des tests
    #   # (remplacer la commande ci-dessous par vos tests)
    - run: curl http://localhost:8080
